dist: focal
os: linux

language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

# install system dependencies here with apt-get.
before_install:
  - sudo ./provision/debian.sh
  - python -m pip install --upgrade pip

# install python dependencies including this package in the travis
# virtualenv
install:
  - ./provision/python3.sh
  - pip install .[pocketsphinx]

# commands to run the testing suite. if any of these fail, travis lets us know
script:
  - cd tests && make && cd -
  - cd tests && pytest && cd -
#  - pycodestyle src/textract/
  - cd docs && make html && cd -

# commands to run after the tests successfully complete
after_success:
  - coveralls
